/**Author and License
 * 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 *
 * @author Ray Njire 
*/
package Clock;

import java.text.SimpleDateFormat;


public class SimpleDigitalClock extends javax.swing.JFrame implements Runnable
{

    /**
     * Creates new form SimpleDigitalClock
     */
    public SimpleDigitalClock() 
    {
        initComponents();
        this.setLocationRelativeTo(null);
        
        Thread thread = new Thread(this);
        thread.start();
        
        System.out.println("Please Note:\n\n"
            + "E->Day if the Week(Tue), "
            + "EEEE->Day of the Week(Tuesday), "
            + "d->Day(6), "
            + "dd->Day(06), "
            + "MM->Month(07), "
            + "MMM->Month(Jul), "
            + "MMMM->Month(July), "
            + "yy->Year(08), "
            + "yyyy->Year(2008), "
            + "hh->12-Hour Clock System, "
            + "HH->24-Hour Clock System, "
            + "mm->Minutes(58), "
            + "ss->Seconds(59), "
            + "S->Milliseconds(989), "
            + "a->(AM/PM), "
            + "G->(BC/AD) \n\n"
            + "Reference: https://docs.oracle.com/javase/7/docs/api/java/text/SimpleDateFormat.html (APA format utaandika mwenyewe)");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        LBLTime = new javax.swing.JLabel();
        LBLDate = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setMaximumSize(new java.awt.Dimension(500, 400));
        setMinimumSize(new java.awt.Dimension(500, 400));
        setPreferredSize(new java.awt.Dimension(500, 400));

        MainPanel.setBackground(new java.awt.Color(0, 0, 0));
        MainPanel.setMaximumSize(new java.awt.Dimension(500, 400));
        MainPanel.setMinimumSize(new java.awt.Dimension(500, 400));
        MainPanel.setPreferredSize(new java.awt.Dimension(500, 400));

        LBLTime.setBackground(new java.awt.Color(0, 0, 0));
        LBLTime.setFont(new java.awt.Font("Algerian", 0, 56)); // NOI18N
        LBLTime.setForeground(new java.awt.Color(0, 255, 102));
        LBLTime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LBLTime.setText("jLabel1");
        LBLTime.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 5, 0, new java.awt.Color(204, 0, 0)));

        LBLDate.setBackground(new java.awt.Color(0, 0, 0));
        LBLDate.setFont(new java.awt.Font("Script MT Bold", 0, 36)); // NOI18N
        LBLDate.setForeground(new java.awt.Color(0, 204, 204));
        LBLDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LBLDate.setText("jLabel2");

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LBLDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(LBLTime, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addComponent(LBLTime, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LBLDate, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 491, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                    
                }
            }
        }
        
        catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(SimpleDigitalClock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() 
        {
            public void run() 
            {
                new SimpleDigitalClock().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LBLDate;
    private javax.swing.JLabel LBLTime;
    private javax.swing.JPanel MainPanel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() 
    {
        //Local Date and Time
        while(true)
        {
            java.util.Date currentDate = new java.util.Date();
            
            SimpleDateFormat timeFormat = new SimpleDateFormat("hh:mm:ss a");
            SimpleDateFormat dateFormat = new SimpleDateFormat("EEEE, dd-MMMM-yyyy");
            
            LBLDate.setText(dateFormat.format(currentDate));
            LBLTime.setText(timeFormat.format(currentDate));
            
        }
    }
}
